// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/protobuf/InternalCommonProtocol.proto

package com.phoenix.protobuf;

public final class InternalCommonProtocol {
  private InternalCommonProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class DBPlayerDetailProto extends
      com.google.protobuf.GeneratedMessage {
    // Use DBPlayerDetailProto.newBuilder() to construct.
    private DBPlayerDetailProto() {
      initFields();
    }
    private DBPlayerDetailProto(boolean noInit) {}
    
    private static final DBPlayerDetailProto defaultInstance;
    public static DBPlayerDetailProto getDefaultInstance() {
      return defaultInstance;
    }
    
    public DBPlayerDetailProto getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.phoenix.protobuf.InternalCommonProtocol.internal_static_phoenix_DBPlayerDetailProto_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.phoenix.protobuf.InternalCommonProtocol.internal_static_phoenix_DBPlayerDetailProto_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto result;
      
      // Construct using com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto();
        return builder;
      }
      
      protected com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto.getDescriptor();
      }
      
      public com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto getDefaultInstanceForType() {
        return com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto) {
          return mergeFrom((com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto other) {
        if (other == com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:phoenix.DBPlayerDetailProto)
    }
    
    static {
      defaultInstance = new DBPlayerDetailProto(true);
      com.phoenix.protobuf.InternalCommonProtocol.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:phoenix.DBPlayerDetailProto)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_phoenix_DBPlayerDetailProto_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_phoenix_DBPlayerDetailProto_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/protobuf/InternalCommonProtocol.pr" +
      "oto\022\007phoenix\032)src/protobuf/ExternalCommo" +
      "nProtocol.proto\"\025\n\023DBPlayerDetailProtoB\030" +
      "\n\024com.phoenix.protobufH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_phoenix_DBPlayerDetailProto_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_phoenix_DBPlayerDetailProto_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_phoenix_DBPlayerDetailProto_descriptor,
              new java.lang.String[] { },
              com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto.class,
              com.phoenix.protobuf.InternalCommonProtocol.DBPlayerDetailProto.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.phoenix.protobuf.ExternalCommonProtocol.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
